"""FIXING USER MODEL

Revision ID: 869f3bb5f8e3
Revises: 34ab475eef58
Create Date: 2024-10-04 13:27:53.917030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869f3bb5f8e3'
down_revision = '34ab475eef58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
