"""Adiciona o modelo User

Revision ID: f0982bf2025f
Revises: a6de000b658e
Create Date: 2024-11-27 15:23:46.205482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0982bf2025f'
down_revision = 'a6de000b658e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otps')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.drop_index('username')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.drop_column('email')

    op.create_table('otps',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('otp_code', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='otps_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
